/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    docs: Doc;
    users: User;
    companies: Company;
    'external-shareholders': ExternalShareholder;
    lei: Lei;
    persons: Person;
    hr_publications: HrPublication;
    network: Network;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    docs: DocsSelect<false> | DocsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    'external-shareholders': ExternalShareholdersSelect<false> | ExternalShareholdersSelect<true>;
    lei: LeiSelect<false> | LeiSelect<true>;
    persons: PersonsSelect<false> | PersonsSelect<true>;
    hr_publications: HrPublicationsSelect<false> | HrPublicationsSelect<true>;
    network: NetworkSelect<false> | NetworkSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  title?: string | null;
  type?:
    | (
        | 'Gesellschaftsvertrag'
        | 'Liste der Gesellschafter'
        | 'Aufsichtsratsliste'
        | 'Jahresabschluss / Bilanz'
        | 'Anmeldung HRA'
        | 'Eintragungsanzeige'
        | 'Weitere Unterlagen'
      )
    | null;
  company?: (string | null) | Company;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  company_name: string;
  hr_status?: ('aktiv' | 'gelöscht' | 'Liquidation' | 'Gesellschaft verlassen') | null;
  hr_dept: 'HRA' | 'HRB';
  hr_number: string;
  hr_court: string;
  headquarter: {
    street: string;
    zipcode: string;
    city: string;
  };
  branches?:
    | {
        street: string;
        zipcode: string;
        city: string;
        id?: string | null;
      }[]
    | null;
  corp_object?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  capital?: number | null;
  represent_rules?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prev_names?:
    | {
        prev_name: string;
        name_upto?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-shareholders".
 */
export interface ExternalShareholder {
  id: number;
  company_name: string;
  registry: 'HRA' | 'HRB' | 'GnR' | 'Behörde' | 'ANDERE';
  registry_number: string;
  registry_court?: string | null;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lei".
 */
export interface Lei {
  id: string;
  company: string | Company;
  lou?:
    | (
        | 'Bloomberg Finance LP (5493001KJTIIGC8Y1R12)'
        | 'Bundesanzeiger Verlag GmbH (39120001KULK7200U106)'
        | 'WM Datenservice (5299000J2N45DDNE4Y28)'
      )
    | null;
  lei_status: 'ISSUED (ausgegeben)' | 'LAPSED (abgelaufen)' | 'INACTIVE' | 'PLANNED';
  first_registration?: string | null;
  /**
   * Die letzte und nächste Verlängerung werden automatisch errechnet.
   */
  auto_renew: boolean;
  /**
   * Nur bei Einträgen ohne automatische Verlängerung angeben.
   */
  last_renewal?: string | null;
  lei_history?:
    | {
        date: string;
        details: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons".
 */
export interface Person {
  id: number;
  first_name: string;
  sir_name: string;
  city: string;
  birthday?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_publications".
 */
export interface HrPublication {
  id: number;
  company?: (string | null) | Company;
  title: string;
  /**
   * Wenn dieses Feld leer ist, wird es automatisch befüllt. Für automatische Änderung Feld leeren.
   */
  summary?: string | null;
  publication_date: string;
  publication_data?:
    | {
        row:
          | 'Firma'
          | 'Sitz, Niederlassung, Zweigniederlassung'
          | 'Gegenstand des Unternehmens'
          | 'Grund- oder Stammkapital'
          | 'Allgemeine Vertretungsregelung'
          | 'Inhaber, persönlich haftende Gesellschafter'
          | 'Geschäftsführer, Vorstand, Leitungsorgan'
          | 'sonstige Vertretungsberechtigte'
          | 'Prokura'
          | 'Rechtsform'
          | 'Beginn, Satzung, Gesellschaftsvertrag'
          | 'Sonstige Rechtsverhältnisse'
          | 'Kommanditisten, Mitglieder';
        value: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        outdated_by?: (number | null) | HrPublication;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  docs?: (number | Doc)[] | null;
  mentioned_companies?: (string | Company)[] | null;
  mentioned_persons?: (number | Person)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network".
 */
export interface Network {
  id: number;
  child_company?: (string | null) | Company;
  leiParent?: boolean | null;
  type:
    | 'Beteiligung'
    | 'Komplementär VH'
    | 'Kommanditist TH'
    | 'Gesellschafter'
    | 'Geschäftsführer'
    | 'CEO'
    | 'COO'
    | 'Einzelprokura'
    | 'Gesamtprokura'
    | 'Filialprokura'
    | 'Andere Vertretungsbefugnis';
  since: string;
  upto?: string | null;
  /**
   * Verbindung zu einer anderen Firma, einer Person oder einem anderen Gesellschafter als Muttergesellschaft
   */
  relation?:
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'external-shareholders';
        value: number | ExternalShareholder;
      } | null)
    | ({
        relationTo: 'persons';
        value: number | Person;
      } | null);
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'external-shareholders';
        value: number | ExternalShareholder;
      } | null)
    | ({
        relationTo: 'lei';
        value: string | Lei;
      } | null)
    | ({
        relationTo: 'persons';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'hr_publications';
        value: number | HrPublication;
      } | null)
    | ({
        relationTo: 'network';
        value: number | Network;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  company?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  id?: T;
  company_name?: T;
  hr_status?: T;
  hr_dept?: T;
  hr_number?: T;
  hr_court?: T;
  headquarter?:
    | T
    | {
        street?: T;
        zipcode?: T;
        city?: T;
      };
  branches?:
    | T
    | {
        street?: T;
        zipcode?: T;
        city?: T;
        id?: T;
      };
  corp_object?: T;
  capital?: T;
  represent_rules?: T;
  prev_names?:
    | T
    | {
        prev_name?: T;
        name_upto?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-shareholders_select".
 */
export interface ExternalShareholdersSelect<T extends boolean = true> {
  company_name?: T;
  registry?: T;
  registry_number?: T;
  registry_court?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lei_select".
 */
export interface LeiSelect<T extends boolean = true> {
  id?: T;
  company?: T;
  lou?: T;
  lei_status?: T;
  first_registration?: T;
  auto_renew?: T;
  last_renewal?: T;
  lei_history?:
    | T
    | {
        date?: T;
        details?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons_select".
 */
export interface PersonsSelect<T extends boolean = true> {
  first_name?: T;
  sir_name?: T;
  city?: T;
  birthday?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hr_publications_select".
 */
export interface HrPublicationsSelect<T extends boolean = true> {
  company?: T;
  title?: T;
  summary?: T;
  publication_date?: T;
  publication_data?:
    | T
    | {
        row?: T;
        value?: T;
        outdated_by?: T;
        id?: T;
      };
  description?: T;
  docs?: T;
  mentioned_companies?: T;
  mentioned_persons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network_select".
 */
export interface NetworkSelect<T extends boolean = true> {
  child_company?: T;
  leiParent?: T;
  type?: T;
  since?: T;
  upto?: T;
  relation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}