name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Biome fixes
        run: pnpm fix

      - name: TypeScript Checks
        run: pnpm tsc-check

      - name: Apply fixes
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
        with:
          commit-message: 'ci: apply fixes'